name: NPM Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          # specify node version and the registry for the RELEASE build
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Build package
        run: |
          npm install
          npm run build
      - name: Register Token
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > $NPM_CONFIG_USERCONFIG
          echo "_auth=$NPM_AUTH_TOKEN" >> $NPM_CONFIG_USERCONFIG
          echo "email=<amine@pixelfactory.io>" >> $NPM_CONFIG_USERCONFIG
          echo "always-auth=true" >> $NPM_CONFIG_USERCONFIG
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        run: npm publish --access public
